### ISSUE TITLE
keyring.backends.macOS.api.Error: (-25244, 'Unknown Error')

### ISSUE THREAD

**Issue by eas342** [spacetelescope/jwst_mast_query#6]
I get a Mac keychain error when running `jwst_query.py` out of the box with Python 3.8.11, astroquery=0.4.5,keyring=23.5.0 on an M1pro mac with MacOS Monterey 12.0.1. It works without an error in a different environment that has Python 3.6.7, astroquery='0.4.2.dev0' and some intel Rosetta thing. It says "python3 wants to use your confidential information stored in astroquery:mast.stsci.edu.token in your keychain. After that, I get an error

Here is the full traceback:
<details>

```
python jwst_query.py                             
Loading config file /Users/~/outside_progs/jwst_mast_query/jwst_mast_query/jwst_query.cfg
INSTRUMENT: nircam
Traceback (most recent call last):
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/backends/macOS/__init__.py", line 40, in set_password
    api.set_generic_password(self.keychain, service, username, password)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/backends/macOS/api.py", line 151, in set_generic_password
    delete_generic_password(name, service, username)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/backends/macOS/api.py", line 172, in delete_generic_password
    Error.raise_for_status(status)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/backends/macOS/api.py", line 114, in raise_for_status
    raise cls(status, "Unknown Error")
keyring.backends.macOS.api.Error: (-25244, 'Unknown Error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jwst_query.py", line 959, in <module>
    query.login(raiseErrorFlag=False)
  File "jwst_query.py", line 302, in login
    self.JwstObs.login(token=token, store_token=True)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/astroquery/query.py", line 150, in login
    bases[0].login(*args, **kwargs)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/astroquery/query.py", line 514, in login
    self._authenticated = self._login(*args, **kwargs)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/astroquery/mast/core.py", line 66, in _login
    return self._auth_obj.login(token, store_token, reenter_token)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/astroquery/mast/auth.py", line 76, in login
    keyring.set_password("astroquery:mast.stsci.edu.token", "masttoken", token)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/Users/~/miniconda3/envs/m1py3p8/lib/python3.8/site-packages/keyring/backends/macOS/__init__.py", line 44, in set_password
    raise PasswordSetError("Can't store password on keychain: " "{}".format(e))
keyring.errors.PasswordSetError: Can't store password on keychain: (-25244, 'Unknown Error')
```

</details>

A way around it is to change this line in `jwst_query.py` 

```
self.JwstObs.login(token=token, store_token=True)
```

to

```
self.JwstObs.login(token=token, store_token=False)
```

**Comment by eas342** [comment]
Good idea, I made a pull request to add a simple switch that sees if the processor is "arm". See:
https://github.com/spacetelescope/jwst_mast_query/pull/8

I don't think you need to store the token if you use the $MAST_API_TOKEN but maybe some users like to do it with a keyring which might be more secure.

**Comment by bhilbert4** [comment]
I also got the keyring error this morning, when attempting to download the nrc-35 data using a linux machine. So maybe we should just set store_token to False all the time so that we don't have to find new logic to deal with each case?
